mutation CreateCard($boardId: ID!, $columnId: ID!, $title: String!, $kind: Kind!)
@invalidates(name: "board", id: $boardId)
@invalidates(name: "boards") {
  createCard(boardId: $boardId, columnId: $columnId, title: $title, kind: $kind) {
    id
    title
    kind
  }
}
